[CmdletBinding()]
param([string]$ScratchRoot='')
$ErrorActionPreference='Stop'
if($ScratchRoot -eq ''){$ScratchRoot=Join-Path $PSScriptRoot '../../.phantom-local/logs/LIVE-002-B/fixture'}
function Check([bool]$ok,[string]$why){if(-not $ok){throw "Fixture FAILED: $why"}}
function Put([string]$path,[string]$body){$p=Join-Path $ScratchRoot $path;$parent=Split-Path $p -Parent;New-Item -ItemType Directory -Path $parent -Force|Out-Null;[IO.File]::WriteAllText($p,$body,(New-Object Text.UTF8Encoding($false)))}
function Digest([string]$s){$sha=[Security.Cryptography.SHA256]::Create();return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($s)))).Replace('-','').ToLowerInvariant()}
New-Item -ItemType Directory -Path $ScratchRoot -Force|Out-Null
$spawn='<list><spawn zone="same-name"><territory minZ="-50" maxZ="50"><node x="100" y="100"/><node x="200" y="100"/><node x="200" y="200"/></territory><npc id="1" count="1"/></spawn><spawn zone="same-name-other"><territory minZ="-50" maxZ="50"><node x="300" y="100"/><node x="400" y="100"/><node x="400" y="200"/></territory><npc id="2" count="1"/></spawn><spawn zone="point"><npc id="3" x="500" y="100" z="0"/></spawn><spawn zone="instance-point"><npc id="4" x="510" y="100" z="0"/></spawn></list>'
Put 'data/spawns/fixture.xml' $spawn
Put 'data/mapregion/fixture.xml' '<list><region name="fixture" locId="777"><map X="20" Y="18"/></region></list>'
Put 'data/zones/fixture.xml' '<list><zone name="Fixture Zone" id="77" minZ="-100" maxZ="100"><node X="0" Y="0"/><node X="1000" Y="0"/><node X="1000" Y="1000"/><node X="0" Y="1000"/></zone></list>'
Put 'data/teleporters/town/123.xml' '<list><npc id="123"><teleport type="NORMAL"><location name="Ruins of Despair" x="500" y="100" z="0"/></teleport></npc></list>'
$coreText='<topology><node id="core.exact" kind="FARMING_AREA" instanceId="0" form="POLYGON" minZ="-50" maxZ="50"><vertex x="100" y="100"/><vertex x="200" y="100"/><vertex x="200" y="200"/><source path="data/spawns/fixture.xml"/></node><node id="core.same-name.false" kind="FARMING_AREA" instanceId="0" form="POLYGON" minZ="-50" maxZ="50"><vertex x="999" y="100"/><vertex x="400" y="100"/><vertex x="400" y="200"/><source path="data/spawns/fixture.xml"/></node><anchor id="core.exact.anchor" role="FARMING" nodeId="core.exact" x="150" y="150" z="0" instanceId="0"/><anchor id="core.false.anchor" role="FARMING" nodeId="core.same-name.false" x="350" y="150" z="0" instanceId="0"/><edge id="core.edge" fromNodeId="core.exact" toNodeId="core.same-name.false" mode="WALK"><source path="data/spawns/fixture.xml"/></edge></topology>'
Put 'data/phantoms/topology/high-five-core.xml' $coreText
$lines=New-Object 'System.Collections.Generic.List[string]';$lines.Add('coverage_key'+"`t"+'source_path'+"`t"+'source_group'+"`t"+'classification'+"`t"+'status'+"`t"+'instance_id'+"`t"+'npc_ids'+"`t"+'npc_level_min'+"`t"+'npc_level_max'+"`t"+'geometry_kind'+"`t"+'geometry_fingerprint'+"`t"+'sample_x'+"`t"+'sample_y'+"`t"+'sample_z')
$groups=@(
    @{name='same-name';npc='1';kind='NPOLY';tokens=@('territory:-50:50:NPoly','vertex:100:100','vertex:200:100','vertex:200:200');x='100';y='100';z='';instance='0'},
    @{name='same-name-other';npc='2';kind='NPOLY';tokens=@('territory:-50:50:NPoly','vertex:300:100','vertex:400:100','vertex:400:200');x='300';y='100';z='';instance='0'},
    @{name='point';npc='3';kind='POINT';tokens=@('point:500:100:0');x='500';y='100';z='0';instance='0'},
    @{name='instance-point';npc='4';kind='POINT';tokens=@('point:510:100:0');x='510';y='100';z='0';instance='1'}
)
foreach($g in $groups){$tokens=[string[]]$g.tokens;[Array]::Sort($tokens,[StringComparer]::Ordinal);$fingerprint=Digest ($tokens -join '|');$key=Digest ($g.name+'|'+$fingerprint);$lines.Add((@($key,'data/spawns/fixture.xml',$g.name,'ORDINARY_WORLD','READY_STATIC',$g.instance,$g.npc,'1','5',$g.kind,$fingerprint,$g.x,$g.y,$g.z) -join "`t"))}
Put 'registry/WORLD_COVERAGE.tsv' (($lines.ToArray() -join "`n")+"`n")
$generator=Join-Path $PSScriptRoot 'Generate-TopologyCandidates.ps1';$root=Join-Path $ScratchRoot 'data';$registry=Join-Path $ScratchRoot 'registry';$first=Join-Path $ScratchRoot 'out-one';$second=Join-Path $ScratchRoot 'out-two'
& $generator -DataRoot $root -RegistryDirectory $registry -OutputDirectory $first -FixtureMode | Out-Null
& $generator -DataRoot $root -RegistryDirectory $registry -OutputDirectory $second -FixtureMode | Out-Null
$a=@(Import-Csv (Join-Path $first 'TOPOLOGY_CANDIDATES.tsv') -Delimiter "`t");$s=@(Import-Csv (Join-Path $first 'WORLD_SPATIAL_ASSOCIATIONS.tsv') -Delimiter "`t");$r=@(Import-Csv (Join-Path $first 'ROUTE_CANDIDATES.tsv') -Delimiter "`t")
Check ($a.Count -eq 4 -and $s.Count -eq 4) 'accounting';Check (@($a|Where-Object ownership -eq 'EXISTING_CORE').Count -eq 1) 'exact core and false positive';Check (@($a|Where-Object candidate_status -eq 'NEEDS_ANCHOR_GEODATA').Count -eq 1) 'polygon anchor blocked';Check (@($s|Where-Object map_region_loc_id -eq '777').Count -eq 4) 'mapregion';Check (@($s|Where-Object zone_ids -eq '77').Count -eq 4) 'zone';Check (@($s|Where-Object nearest_landmark_label -eq 'Ruins of Despair').Count -eq 4) 'source landmark';Check (@($r|Where-Object candidate_mode -eq 'TELEPORT_FACT').Count -eq 1) 'factual teleport';Check (@($r|Where-Object {$_.candidate_mode -in @('LOCAL_WALK','REGION_LINK') -and $_.validation_status -ne 'NEEDS_GEODATA'}).Count -eq 0) 'walk status'
Check (@($r|Where-Object {$_.candidate_mode -eq 'TELEPORT_FACT' -and $_.from_kind -eq 'TELEPORTER_NPC' -and $_.to_kind -eq 'SOURCE_LOCATION'}).Count -eq 1) 'teleport direction'
$instanceNode=($a|Where-Object instance_id -eq '1').node_id;Check (@($r|Where-Object {$_.candidate_mode -in @('LOCAL_WALK','REGION_LINK') -and ($_.from_id -eq $instanceNode -or $_.to_id -eq $instanceNode)}).Count -eq 0) 'instance isolation'
foreach($name in @('WORLD_SPATIAL_ASSOCIATIONS.tsv','TOPOLOGY_CANDIDATES.tsv','ROUTE_CANDIDATES.tsv','TOPOLOGY_CANDIDATE_MANIFEST.json')){Check ((Get-FileHash (Join-Path $first $name)).Hash -eq (Get-FileHash (Join-Path $second $name)).Hash) "determinism $name"}
$generated=@($a|Where-Object ownership -eq 'GENERATED_CANDIDATE'|ForEach-Object node_id);$collision=$generated[0];Put 'data/phantoms/topology/high-five-core.xml' ($coreText.Replace('</topology>',('<node id="'+$collision+'" kind="CITY" instanceId="0"/></topology>')));$rejected=$false;try {& $generator -DataRoot $root -RegistryDirectory $registry -OutputDirectory (Join-Path $ScratchRoot 'collision') -FixtureMode | Out-Null}catch{if($_.Exception.Message -match 'Core/generated ID collision'){$rejected=$true}else{throw}};Check $rejected 'core/generated ID collision rejection';Put 'data/phantoms/topology/high-five-core.xml' $coreText
$reordered='<list>'+ (($spawn -replace '^<list>','' -replace '</list>$','') -replace '(<spawn zone="same-name">.*?</spawn>)(<spawn zone="same-name-other">.*?</spawn>)','$2$1') + '</list>';Put 'data/spawns/fixture.xml' $reordered
& $generator -DataRoot $root -RegistryDirectory $registry -OutputDirectory (Join-Path $ScratchRoot 'reordered') -FixtureMode | Out-Null
$reorderedRows=@(Import-Csv (Join-Path $ScratchRoot 'reordered/TOPOLOGY_CANDIDATES.tsv') -Delimiter "`t");Check ((@($reorderedRows|Where-Object ownership -eq 'GENERATED_CANDIDATE'|ForEach-Object node_id) -join '|') -eq ($generated -join '|')) 'stable generated IDs after source reorder';Put 'data/spawns/fixture.xml' $spawn
$registryText=[IO.File]::ReadAllText((Join-Path $registry 'WORLD_COVERAGE.tsv'));Put 'registry/WORLD_COVERAGE.tsv' ($registryText.Replace('data/spawns/fixture.xml','data\spawns\fixture.xml'))
& $generator -DataRoot $root -RegistryDirectory $registry -OutputDirectory (Join-Path $ScratchRoot 'normalized') -FixtureMode | Out-Null
$normalizedRows=@(Import-Csv (Join-Path $ScratchRoot 'normalized/TOPOLOGY_CANDIDATES.tsv') -Delimiter "`t");foreach($id in $generated){Check (@($normalizedRows|Where-Object node_id -eq $id).Count -eq 1) 'stable generated ID after path separator normalization'};Put 'registry/WORLD_COVERAGE.tsv' $registryText
"TOPOLOGY fixture GREEN: 4/4 accounting, exact-core, false-positive, mapregion, zone, landmark, anchor, route, instance, direction, collision, reorder, byte identity"
